services:
  web:
    build: .
    ports:
      - "1234:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: registration
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./registration.sql:/docker-entrypoint-initdb.d/registration.sql

volumes:
  db_data: